export const COUNSELING_DETAIL_REQUEST = 'COUNSELING_DETAIL_REQUEST';
export const COUNSELING_DETAIL_SUCESS = 'COUNSELING_DETAIL_SUCESS';
export const COUNSELING_DETAIL_FAIL = 'COUNSELING_DETAIL_FAIL';
export const COUNSELING_DETAIL_RESET = 'COUNSELING_DETAIL_RESET';


export const COUNSELING_DETAIL_ID_REQUEST = 'COUNSELING_DETAIL_ID_REQUEST';
export const COUNSELING_DETAIL_ID_SUCESS = 'COUNSELING_DETAIL_ID_SUCESS';
export const COUNSELING_DETAIL_ID_FAIL = 'COUNSELING_DETAIL_ID_FAIL';
export const COUNSELING_DETAIL_ID_RESET = 'COUNSELING_DETAIL_ID_ReSET';


export const COUNSELING_DELETE_REQUEST = "COUNSELING_DELETE_REQUEST";
export const COUNSELING_DELETE_SUCCESS = "COUNSELING_DELETE_SUCCESS";
export const COUNSELING_DELETE_FAIL = "COUNSELING_DELETE_FAIL";
export const COUNSELING_DELETE_RESET = "COUNSELING_DELETE_RESET";

export const COUNSELING_CREATE_REQUEST = 'COUNSELING_CREATE_REQUEST';
export const COUNSELING_CREATE_SUCESS = 'COUNSELING_CREATE_SUCESS';
export const COUNSELING_CREATE_FAIL = 'COUNSELING_CREATE_FAIL';
export const COUNSELING_CREATE_RESET = 'COUNSELING_CREATE_RESET';