export const DEMOCLASS_DETAIL_REQUEST = 'DEMOCLASS_DETAIL_REQUEST';
export const DEMOCLASS_DETAIL_SUCESS = 'DEMOCLASS_DETAIL_SUCESS';
export const DEMOCLASS_DETAIL_FAIL = 'DEMOCLASS_DETAIL_FAIL';
export const DEMOCLASS_DETAIL_RESET = 'DEMOCLASS_DETAIL_RESET';


export const DEMOCLASS_DETAIL_ID_REQUEST = 'DEMOCLASS_DETAIL_ID_REQUEST';
export const DEMOCLASS_DETAIL_ID_SUCESS = 'DEMOCLASS_DETAIL_ID_SUCESS';
export const DEMOCLASS_DETAIL_ID_FAIL = 'DEMOCLASS_DETAIL_ID_FAIL';
export const DEMOCLASS_DETAIL_ID_RESET = 'DEMOCLASS_DETAIL_ID_RESET';


export const DEMOCLASS_DELETE_REQUEST = "DEMOCLASS_DELETE_REQUEST";
export const DEMOCLASS_DELETE_SUCCESS = "DEMOCLASS_DELETE_SUCCESS";
export const DEMOCLASS_DELETE_FAIL = "DEMOCLASS_DELETE_FAIL";
export const DEMOCLASS_DELETE_RESET = "DEMOCLASS_DELETE_RESET";

export const DEMOCLASS_CREATE_REQUEST = 'DEMOCLASS_CREATE_REQUEST';
export const DEMOCLASS_CREATE_SUCESS = 'DEMOCLASS_CREATE_SUCESS';
export const DEMOCLASS_CREATE_FAIL = 'DEMOCLASS_CREATE_FAIL';
export const DEMOCLASS_CREATE_RESET = 'DEMOCLASS_CREATE_RESET';