export const FORM_DETAIL_REQUEST = 'FORM_DETAIL_REQUEST';
export const FORM_DETAIL_SUCESS = 'FORM_DETAIL_SUCESS';
export const FORM_DETAIL_FAIL = 'FORM_DETAIL_FAIL';
export const FORM_DETAIL_RESET = 'FORM_DETAIL_RESET';

export const FORM_DETAIL_ID_REQUEST = 'FORM_DETAIL_ID_REQUEST';
export const FORM_DETAIL_ID_SUCESS = 'FORM_DETAIL_ID_SUCESS';
export const FORM_DETAIL_ID_FAIL = 'FORM_DETAIL_ID_FAIL';
export const FORM_DETAIL_ID_RESET = 'FORM_DETAIL_ID_RESET';


export const FORM_DELETE_REQUEST = "FORM_DELETE_REQUEST";
export const FORM_DELETE_SUCCESS = "FORM_DELETE_SUCCESS";
export const FORM_DELETE_FAIL = "FORM_DELETE_FAIL";
export const FORM_DELETE_RESET = "FORM_DELETE_RESET";