export { default as Hero } from './Hero';
export { default as QuickStart } from './QuickStart';
export { default as Features } from './Features';
export { default as VideoSection } from './VideoSection';
export { default as Works} from './Works';
export { default as AskExpert } from './AskExpert';
export { default as Categories } from './Categories';
export { default as Reviews } from './Reviews';
export { default as Work } from './Work';
export { default as Process } from './Process';
export { default as ProfessionalCourse } from './ProfessionalCourse';